--------------------------------------------------------
--  파일이 생성됨 - 화요일-3월-26-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table AUTH_ADM_CODE_DETAIL
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_ADM_CODE_DETAIL" 
   (	"CODE_MASTER" VARCHAR2(100 BYTE), 
	"CODE" VARCHAR2(100 BYTE), 
	"CODE_NAME" VARCHAR2(20 BYTE), 
	"REG_DATE" DATE, 
	"REG_ID" VARCHAR2(30 BYTE), 
	"MOD_DATE" DATE, 
	"MOD_ID" VARCHAR2(30 BYTE), 
	"PRIORITY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_DETAIL"."CODE_MASTER" IS '마스터코드';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_DETAIL"."CODE" IS '상세코드';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_DETAIL"."CODE_NAME" IS '상세코드명';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_DETAIL"."REG_DATE" IS '등록일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_DETAIL"."REG_ID" IS '등록자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_DETAIL"."MOD_DATE" IS '수정일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_DETAIL"."MOD_ID" IS '수정자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_DETAIL"."PRIORITY" IS '정렬순서';
 
   COMMENT ON TABLE "HECATE"."AUTH_ADM_CODE_DETAIL"  IS 'admin 공통코드상세';
--------------------------------------------------------
--  DDL for Table AUTH_ADM_MANAGER_GROUP
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" 
   (	"ORG_C" VARCHAR2(3 BYTE) DEFAULT '001', 
	"ADMIN_GRP_ID" NUMBER, 
	"ADMIN_GRP_NM" VARCHAR2(20 BYTE), 
	"ADMIN_GRP_INFO" VARCHAR2(100 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"PRIORITY" NUMBER, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"REG_ID" VARCHAR2(30 BYTE), 
	"MOD_DATE" DATE DEFAULT SYSDATE, 
	"MOD_ID" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."ORG_C" IS '';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."ADMIN_GRP_ID" IS '관리자그룹ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."ADMIN_GRP_NM" IS '관리자그룹명';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."ADMIN_GRP_INFO" IS '그룹설명';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."USE_YN" IS '사용여부';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."PRIORITY" IS '우선순위';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."REG_DATE" IS '등록일자';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."REG_ID" IS '등록자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."MOD_DATE" IS '수정일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_GROUP"."MOD_ID" IS '수정자ID';
 
   COMMENT ON TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP"  IS 'ADMIN 그룹관리';
--------------------------------------------------------
--  DDL for Table AUTH_ADM_CODE_MASTER
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_ADM_CODE_MASTER" 
   (	"CODE_MASTER" VARCHAR2(100 BYTE), 
	"CODE_NAME" VARCHAR2(100 BYTE), 
	"REG_DATE" DATE, 
	"REG_ID" VARCHAR2(30 BYTE), 
	"MOD_DATE" DATE, 
	"MOD_ID" VARCHAR2(30 BYTE), 
	"PRIORITY" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_MASTER"."CODE_MASTER" IS '마스터코드';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_MASTER"."CODE_NAME" IS '공통코드명';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_MASTER"."REG_DATE" IS '등록일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_MASTER"."REG_ID" IS '등록자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_MASTER"."MOD_DATE" IS '수정일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_MASTER"."MOD_ID" IS '수정자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_CODE_MASTER"."PRIORITY" IS '정렬순서';
 
   COMMENT ON TABLE "HECATE"."AUTH_ADM_CODE_MASTER"  IS 'admin 공통코드마스터';
--------------------------------------------------------
--  DDL for Table AUTH_ADM_MANAGER_INFO
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" 
   (	"ORG_C" VARCHAR2(3 BYTE) DEFAULT '001', 
	"ADMIN_ID" VARCHAR2(30 BYTE), 
	"ADMIN_PW" VARCHAR2(50 BYTE), 
	"ADMIN_NM" VARCHAR2(20 BYTE), 
	"ADMIN_GRP_ID" NUMBER, 
	"MOBILE_NO" VARCHAR2(16 BYTE), 
	"MAIL_ADDR" VARCHAR2(30 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"PRIORITY" NUMBER, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"REG_ID" VARCHAR2(30 BYTE), 
	"MOD_DATE" DATE DEFAULT SYSDATE, 
	"MOD_ID" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."ORG_C" IS '';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."ADMIN_ID" IS '관리자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."ADMIN_PW" IS '관리자비밀번호';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."ADMIN_NM" IS '관리자명';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."ADMIN_GRP_ID" IS '관리자그룹ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."MOBILE_NO" IS '휴대폰번호';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."MAIL_ADDR" IS '이메일주소';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."USE_YN" IS '사용여부';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."PRIORITY" IS '우선순위';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."REG_DATE" IS '등록일자';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."REG_ID" IS '등록자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."MOD_DATE" IS '수정일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MANAGER_INFO"."MOD_ID" IS '수정자ID';
 
   COMMENT ON TABLE "HECATE"."AUTH_ADM_MANAGER_INFO"  IS 'ADMIN 계정관리';
--------------------------------------------------------
--  DDL for Table AUTH_ADM_MENU_AUTH
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_ADM_MENU_AUTH" 
   (	"ORG_C" VARCHAR2(3 BYTE) DEFAULT '001', 
	"ADMIN_GRP_ID" NUMBER, 
	"MENU_ID" NUMBER, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"REG_ID" VARCHAR2(30 BYTE), 
	"MOD_DATE" DATE DEFAULT SYSDATE, 
	"MOD_ID" VARCHAR2(30 BYTE), 
	"AUTH_TYPE" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_AUTH"."ORG_C" IS '';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_AUTH"."ADMIN_GRP_ID" IS '관리자그룹ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_AUTH"."MENU_ID" IS '메뉴ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_AUTH"."REG_DATE" IS '등록일자';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_AUTH"."REG_ID" IS '등록자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_AUTH"."MOD_DATE" IS '수정일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_AUTH"."MOD_ID" IS '수정자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_AUTH"."AUTH_TYPE" IS '권한타입코드';
 
   COMMENT ON TABLE "HECATE"."AUTH_ADM_MENU_AUTH"  IS 'ADMIN 메뉴권한';
--------------------------------------------------------
--  DDL for Table AUTH_ADM_MENU_INFO
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_ADM_MENU_INFO" 
   (	"ORG_C" VARCHAR2(3 BYTE) DEFAULT '001', 
	"MENU_ID" NUMBER, 
	"MENU_NM" VARCHAR2(30 BYTE), 
	"PARENT_MENU_ID" NUMBER, 
	"MENU_LEVEL" NUMBER DEFAULT 1, 
	"MENU_URL" VARCHAR2(50 BYTE), 
	"USE_YN" VARCHAR2(1 BYTE) DEFAULT 'Y', 
	"PRIORITY" NUMBER, 
	"REG_DATE" DATE DEFAULT SYSDATE, 
	"REG_ID" VARCHAR2(30 BYTE), 
	"MOD_DATE" DATE DEFAULT SYSDATE, 
	"MOD_ID" VARCHAR2(30 BYTE), 
	"MENU_IMG" VARCHAR2(1000 BYTE), 
	"DEL_ABLE_YN" VARCHAR2(1 BYTE) DEFAULT 'N'
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."ORG_C" IS '';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."MENU_ID" IS '메뉴ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."MENU_NM" IS '메뉴명';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."PARENT_MENU_ID" IS '상위메뉴ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."MENU_LEVEL" IS '메뉴레벨';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."MENU_URL" IS '메뉴경로';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."USE_YN" IS '사용여부';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."PRIORITY" IS '우선순위';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."REG_DATE" IS '등록일자';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."REG_ID" IS '등록자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."MOD_DATE" IS '수정일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."MOD_ID" IS '수정자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."MENU_IMG" IS '메뉴이미지';
 
   COMMENT ON COLUMN "HECATE"."AUTH_ADM_MENU_INFO"."DEL_ABLE_YN" IS '삭제가능여부';
 
   COMMENT ON TABLE "HECATE"."AUTH_ADM_MENU_INFO"  IS 'ADMIN 메뉴관리';
--------------------------------------------------------
--  DDL for Table AUTH_CERT_DSSUE_HISTORY
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" 
   (	"DSSUE_SEQ" NUMBER(10,0), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"DEVICE_ID" VARCHAR2(100 BYTE), 
	"BC_ID" VARCHAR2(100 BYTE), 
	"SIGN_DOC" VARCHAR2(3000 BYTE), 
	"DSSUE_TYPE" VARCHAR2(2 BYTE), 
	"REG_DATE" DATE, 
	"REG_ID" VARCHAR2(30 BYTE), 
	"BC_TRANSACTION_HASH" VARCHAR2(500 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."DSSUE_SEQ" IS '폐기이력 시퀀스';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."USER_ID" IS '사용자 아이디';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."DEVICE_ID" IS '기기 아이디';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."BC_ID" IS '블록체인 아이디';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."SIGN_DOC" IS '인증서 폐기 서명 데이터';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."DSSUE_TYPE" IS '폐기구분';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."REG_DATE" IS '등록일자';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."REG_ID" IS '등록자';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_DSSUE_HISTORY"."BC_TRANSACTION_HASH" IS '인증서 폐기 트렌젝션 Hash';
 
   COMMENT ON TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY"  IS '인증서 폐기이력';
--------------------------------------------------------
--  DDL for Table AUTH_CERT_ISSUE_HISTORY
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" 
   (	"ISSUE_SEQ" NUMBER(10,0), 
	"USER_ID" VARCHAR2(100 BYTE), 
	"DEVICE_ID" VARCHAR2(100 BYTE), 
	"BC_ID" VARCHAR2(100 BYTE), 
	"CERT_INFO" VARCHAR2(3000 BYTE), 
	"BC_TRANSACTION_HASH" VARCHAR2(500 BYTE), 
	"REG_DATE" DATE DEFAULT sysdate, 
	"REG_ID" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_CERT_ISSUE_HISTORY"."ISSUE_SEQ" IS '발급이력 시퀀스';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_ISSUE_HISTORY"."USER_ID" IS '사용자 아이디';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_ISSUE_HISTORY"."DEVICE_ID" IS '기기 아이디';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_ISSUE_HISTORY"."BC_ID" IS '블록체인 아이디';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_ISSUE_HISTORY"."CERT_INFO" IS '인증서 정보 발급정보';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_ISSUE_HISTORY"."BC_TRANSACTION_HASH" IS '인증서 발급 트렌젝션 Hash';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_ISSUE_HISTORY"."REG_DATE" IS '등록일자';
 
   COMMENT ON COLUMN "HECATE"."AUTH_CERT_ISSUE_HISTORY"."REG_ID" IS '등록자ID';
 
   COMMENT ON TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY"  IS '인증서 발급이력';
--------------------------------------------------------
--  DDL for Table AUTH_USER_INFO
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_USER_INFO" 
   (	"EMAIL_ADDR" VARCHAR2(30 BYTE), 
	"DEVICE_ID" VARCHAR2(100 BYTE), 
	"BC_ID" VARCHAR2(100 BYTE), 
	"CELL_NO" VARCHAR2(11 BYTE), 
	"USER_NAME" VARCHAR2(100 BYTE), 
	"BIRTH_DATE" CHAR(8 BYTE), 
	"UNDER14_FLAG" CHAR(1 BYTE), 
	"AGENT_NAME" VARCHAR2(20 BYTE), 
	"AGENT_BIRTH_DATE" CHAR(8 BYTE), 
	"MARKETING_RECV_AGMT_FLAG" CHAR(1 BYTE), 
	"SERVICE_AGMT_FLAG" CHAR(1 BYTE), 
	"ETRADE_AGMT_FLAG" CHAR(1 BYTE), 
	"PRIVATE_INFO_AGMT_FLAG" CHAR(1 BYTE), 
	"BC_PRIVATE_KEY" VARCHAR2(100 BYTE), 
	"USER_PASSWORD_HARF" VARCHAR2(100 BYTE), 
	"BC_WALLET_ADDRESS" VARCHAR2(100 BYTE), 
	"BC_TRANSACTION_HASH" VARCHAR2(100 BYTE), 
	"IS_USE" CHAR(1 BYTE), 
	"REG_DATE" DATE, 
	"MOD_DATE" DATE, 
	"REG_ID" VARCHAR2(30 BYTE), 
	"MOD_ID" VARCHAR2(30 BYTE), 
	"GENDER_FLAG" VARCHAR2(1 BYTE), 
	"REG_PATH" VARCHAR2(2 BYTE), 
	"LAST_LOGIN" DATE, 
	"CI" VARCHAR2(88 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Table AUTH_USER_EVENT_LOG
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_USER_EVENT_LOG" 
   (	"IDX" NUMBER DEFAULT 1, 
	"USER_ID" VARCHAR2(30 BYTE), 
	"EVENT_CODE" VARCHAR2(10 BYTE), 
	"REG_DATE" DATE DEFAULT SYSDATE
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_USER_EVENT_LOG"."USER_ID" IS '사용자 아이디';
 
   COMMENT ON COLUMN "HECATE"."AUTH_USER_EVENT_LOG"."EVENT_CODE" IS '이벤트 코드';
 
   COMMENT ON COLUMN "HECATE"."AUTH_USER_EVENT_LOG"."REG_DATE" IS '이벤트 등록일';
 
   COMMENT ON TABLE "HECATE"."AUTH_USER_EVENT_LOG"  IS '블록체인 서비스 가입자 이벤트 로그 ';
--------------------------------------------------------
--  DDL for Table AUTH_TMP
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_TMP" 
   (	"MENU_CODE" NUMBER, 
	"MENU_TITLE" VARCHAR2(30 BYTE), 
	"MENU_URL" VARCHAR2(100 BYTE), 
	"MENU_PARENT" NUMBER, 
	"MENU_SEQ" NUMBER, 
	"MENU_LEVEL" NUMBER
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Table AUTH_FAIL_HISTORY
--------------------------------------------------------

  CREATE TABLE "HECATE"."AUTH_FAIL_HISTORY" 
   (	"FAIL_SEQ" NUMBER(10,0), 
	"FAIL_TYPE" VARCHAR2(10 BYTE), 
	"FAIL_DATA" VARCHAR2(3000 BYTE), 
	"FAIL_FINAL" VARCHAR2(1 BYTE) DEFAULT 'N', 
	"FAIL_CAUSE" VARCHAR2(1000 BYTE), 
	"FAIL_REG_DATE" DATE, 
	"FAIL_MOD_DATE" DATE, 
	"FAIL_REG_ID" VARCHAR2(30 BYTE), 
	"FAIL_MOD_ID" VARCHAR2(30 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
 

   COMMENT ON COLUMN "HECATE"."AUTH_FAIL_HISTORY"."FAIL_TYPE" IS '실패 타입';
 
   COMMENT ON COLUMN "HECATE"."AUTH_FAIL_HISTORY"."FAIL_DATA" IS '실패 데이터';
 
   COMMENT ON COLUMN "HECATE"."AUTH_FAIL_HISTORY"."FAIL_FINAL" IS '최종 실패 여부';
 
   COMMENT ON COLUMN "HECATE"."AUTH_FAIL_HISTORY"."FAIL_CAUSE" IS '실패 사유';
 
   COMMENT ON COLUMN "HECATE"."AUTH_FAIL_HISTORY"."FAIL_REG_DATE" IS '등록일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_FAIL_HISTORY"."FAIL_MOD_DATE" IS '수정일';
 
   COMMENT ON COLUMN "HECATE"."AUTH_FAIL_HISTORY"."FAIL_REG_ID" IS '등록자ID';
 
   COMMENT ON COLUMN "HECATE"."AUTH_FAIL_HISTORY"."FAIL_MOD_ID" IS '수정자ID';
--------------------------------------------------------
--  DDL for Index AUTH_ADM_CODE_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."AUTH_ADM_CODE_DETAIL_PK" ON "HECATE"."AUTH_ADM_CODE_DETAIL" ("CODE_MASTER", "CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index SYS_C00178255
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."SYS_C00178255" ON "HECATE"."AUTH_ADM_MANAGER_GROUP" ("ORG_C", "ADMIN_GRP_NM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index AUTH_ADM_CODE_MASTER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."AUTH_ADM_CODE_MASTER_PK" ON "HECATE"."AUTH_ADM_CODE_MASTER" ("CODE_MASTER") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index SYS_C00178264
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."SYS_C00178264" ON "HECATE"."AUTH_ADM_MANAGER_INFO" ("ORG_C", "ADMIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index SYS_C00178272
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."SYS_C00178272" ON "HECATE"."AUTH_ADM_MENU_AUTH" ("ORG_C", "ADMIN_GRP_ID", "MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index AUTH_ADM_MENU_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."AUTH_ADM_MENU_INFO_PK" ON "HECATE"."AUTH_ADM_MENU_INFO" ("ORG_C", "MENU_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index AUTH_CERT_DSSUE_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."AUTH_CERT_DSSUE_HISTORY_PK" ON "HECATE"."AUTH_CERT_DSSUE_HISTORY" ("DSSUE_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index AUTH_CERT_ISSUE_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."AUTH_CERT_ISSUE_HISTORY_PK" ON "HECATE"."AUTH_CERT_ISSUE_HISTORY" ("ISSUE_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index AUTH_USER_INFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."AUTH_USER_INFO_PK" ON "HECATE"."AUTH_USER_INFO" ("EMAIL_ADDR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  DDL for Index AUTH_FAIL_HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HECATE"."AUTH_FAIL_HISTORY_PK" ON "HECATE"."AUTH_FAIL_HISTORY" ("FAIL_SEQ") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE" ;
--------------------------------------------------------
--  Constraints for Table AUTH_ADM_CODE_DETAIL
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_ADM_CODE_DETAIL" ADD CONSTRAINT "AUTH_ADM_CODE_DETAIL_PK" PRIMARY KEY ("CODE_MASTER", "CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
 
  ALTER TABLE "HECATE"."AUTH_ADM_CODE_DETAIL" MODIFY ("CODE_MASTER" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_ADM_MANAGER_GROUP
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" MODIFY ("ORG_C" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" MODIFY ("ADMIN_GRP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" MODIFY ("ADMIN_GRP_NM" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" MODIFY ("USE_YN" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" MODIFY ("REG_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" MODIFY ("REG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" MODIFY ("MOD_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" MODIFY ("MOD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_GROUP" ADD PRIMARY KEY ("ORG_C", "ADMIN_GRP_NM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_ADM_CODE_MASTER
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_ADM_CODE_MASTER" ADD CONSTRAINT "AUTH_ADM_CODE_MASTER_PK" PRIMARY KEY ("CODE_MASTER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
 
  ALTER TABLE "HECATE"."AUTH_ADM_CODE_MASTER" MODIFY ("CODE_MASTER" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_CODE_MASTER" MODIFY ("CODE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_ADM_MANAGER_INFO
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" MODIFY ("ORG_C" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" MODIFY ("ADMIN_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" MODIFY ("ADMIN_GRP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" MODIFY ("USE_YN" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" MODIFY ("REG_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" MODIFY ("REG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" MODIFY ("MOD_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" MODIFY ("MOD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MANAGER_INFO" ADD PRIMARY KEY ("ORG_C", "ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_ADM_MENU_AUTH
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_ADM_MENU_AUTH" MODIFY ("ORG_C" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_AUTH" MODIFY ("ADMIN_GRP_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_AUTH" MODIFY ("MENU_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_AUTH" MODIFY ("REG_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_AUTH" MODIFY ("REG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_AUTH" MODIFY ("MOD_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_AUTH" MODIFY ("MOD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_AUTH" ADD PRIMARY KEY ("ORG_C", "ADMIN_GRP_ID", "MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTH_ADM_MENU_INFO
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" ADD CONSTRAINT "AUTH_ADM_MENU_INFO_PK" PRIMARY KEY ("ORG_C", "MENU_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("ORG_C" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("MENU_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("MENU_NM" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("MENU_LEVEL" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("USE_YN" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("REG_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("REG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("MOD_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("MOD_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_ADM_MENU_INFO" MODIFY ("DEL_ABLE_YN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_CERT_DSSUE_HISTORY
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" ADD CONSTRAINT "AUTH_CERT_DSSUE_HISTORY_PK" PRIMARY KEY ("DSSUE_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
 
  ALTER TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" MODIFY ("DSSUE_SEQ" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" MODIFY ("BC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" MODIFY ("SIGN_DOC" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" MODIFY ("REG_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_DSSUE_HISTORY" MODIFY ("REG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_CERT_ISSUE_HISTORY
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" ADD CONSTRAINT "AUTH_CERT_ISSUE_HISTORY_PK" PRIMARY KEY ("ISSUE_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
 
  ALTER TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" MODIFY ("ISSUE_SEQ" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" MODIFY ("DEVICE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" MODIFY ("BC_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" MODIFY ("CERT_INFO" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" MODIFY ("REG_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_CERT_ISSUE_HISTORY" MODIFY ("REG_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_USER_INFO
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_USER_INFO" ADD CONSTRAINT "AUTH_USER_INFO_PK" PRIMARY KEY ("EMAIL_ADDR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("EMAIL_ADDR" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("CELL_NO" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("USER_NAME" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("BIRTH_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("UNDER14_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("SERVICE_AGMT_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("ETRADE_AGMT_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("PRIVATE_INFO_AGMT_FLAG" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("IS_USE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("REG_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("MOD_DATE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("REG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_INFO" MODIFY ("MOD_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_USER_EVENT_LOG
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_USER_EVENT_LOG" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_EVENT_LOG" MODIFY ("EVENT_CODE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_USER_EVENT_LOG" MODIFY ("REG_DATE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AUTH_FAIL_HISTORY
--------------------------------------------------------

  ALTER TABLE "HECATE"."AUTH_FAIL_HISTORY" ADD CONSTRAINT "AUTH_FAIL_HISTORY_PK" PRIMARY KEY ("FAIL_SEQ")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "HECATE"  ENABLE;
 
  ALTER TABLE "HECATE"."AUTH_FAIL_HISTORY" MODIFY ("FAIL_SEQ" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_FAIL_HISTORY" MODIFY ("FAIL_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_FAIL_HISTORY" MODIFY ("FAIL_FINAL" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_FAIL_HISTORY" MODIFY ("FAIL_REG_ID" NOT NULL ENABLE);
 
  ALTER TABLE "HECATE"."AUTH_FAIL_HISTORY" MODIFY ("FAIL_MOD_ID" NOT NULL ENABLE);
