eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9102/eureka/
      
rabbitmq:
    host: localhost    
    port: 5672
    username: springconfigbus
    password: springconfigbus1!   


########TEST
test : ㅇㅇㅇㅇ?ghhh
